export const appRoutesConstants = {
    Login: "/login",
    LoginContent: "/loginContent",
    LoginWithOtp: "/loginWithOtp",
    UpdatePassword: "/update",
    ForgetPassword: "/forget",
    Signup: "/signup",
    Layout: "/layout",
    Home: "",
    About: "/about",
    Event: "/event",
    Cart: "/cart",
    History: "/history",
    Success: "/success",
    CreateEvent: "/createEvent",
    AddEvent:"/addEvent",
    Dashboard: "/dashboard",
    EventOrganizer: "/eventOrganizer",
    Payout: "/payout",
    Approval: "/approval",
    HistoryOrganizer: "/historyOrganizer"
};
