
export const appRoutesConstants = {
    Login: "/login",
    LoginContent: "/loginContent",
    LoginWithOtp: "/loginWithOtp",
    UpdatePassword: "/update",
    ForgetPassword: "/forget",
    Signup: "/signup",
    Layout: "/layout",
    Home: "",
    About: "/about",
    Event: "/event",
    Cart: "/cart",
    History: "/history",
    Success: "/success",
    CreateEvent: "/createEvent",
    AddEvent:"/addEvent",
    EventOrganizer: "/eventOrganizer",
    Payout: "/payout",
    Approval: "/approval",
    HistoryOrganizer: "/historyOrganizer",
    OverviewAdmin: "/overviewadmin",
    Blog: "/blog",
    EventsAdmin: "/eventsAdmin",
    ApprovalAdmin: "/approvalAdmin",
    HistoryAdmin: "/historyAdmin",
    PlacesAdmin: "/placesAdmin",
};
